version: '3.9'

services:
  db:
    networks:
      - expense-tracker
    image: postgres:16.2
    build:
      context: .
      # dockerfile: ./DockerFile.postgres.setting
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense_tracker
    volumes:
      - ./data/db:/var/lib/postgresql/data

networks:
  expense-tracker:
