version: '3.9'

services:
  db:
    networks:
      - expense-tracker
    image: postgres:16.2
    build:
      context: .
      # dockerfile: ./DockerFile.postgres.setting
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense_tracker
    volumes:
      - ./data/db:/var/lib/postgresql/data
  # mysql:
  #   image: mysql:8.4
  #   container_name: mysql_db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: db_crud
  #     MYSQL_USER: user_crud
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3307:3306"

networks:
  expense-tracker:
