name: Build API Image and Push

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      # clonar archvivos del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # instalar docker para contruir la imagen
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Loguearse en docker hub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Crea una variable tag donde para la imagen de docker. Le adjunta el hash del commit y ademas el lastest
      - name: Set image tags
        id: tag
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "image=${DOCKER_USERNAME}/${DOCKER_REPO}" >> $GITHUB_OUTPUT

      # Construye la imagen con el Dockerfile y el tag generado
      - name: Tag image as latest
        run: |
          docker tag ${{ steps.tag.outputs.image }}:${{ steps.tag.outputs.short_sha }} \
                 ${{ steps.tag.outputs.image }}:latest

      - name: Push Docker image with commit tag
        run: docker push ${{ steps.tag.outputs.image }}:${{ steps.tag.outputs.short_sha }}

      - name: Push Docker image with latest tag
        run: docker push ${{ steps.tag.outputs.image }}:latest
